### ISSUE TITLE
Spectra Altium

### ISSUE THREAD

**Issue by sam-richardson** [OpenEIT/EIT_EE#5]
Are the Altium files for  the most up to date PCB (Spectra) available?

**Comment by JeanRintoul** [comment]
they are not currently available. I intend to make a separate repository at some point in the future for them, but am unclear what level of support to also provide on this, as I am already supporting the dashboard, firmware etc. The repository here has an 8 electrode version, an example flex array and also the schematic of Spectra.pdf in this repository is that is up to date, and is the production version of the Spectra board containing all technical data. If you have a competent EE on hand, you will be able to recreate/alter it from this data.
